use bookstore;
insert into books values(NULL,'HTML5+CSS3从入门到精通（附光盘）',52.60);
insert into books values(NULL,'HTML5权威指南',112.30);
insert into books values(NULL,'HTML CSS JavaScript网页制作从入门到精通',34.60);
insert into books values(NULL,'Head First HTML与CSS（第2版）',83.70);
insert into books values(NULL,'Web设计与前端开发秘籍：HTML CSS JavaScript jQuery 构建网站（套装共2册）',114.30);
insert into books values(NULL,'疯狂HTML 5/CSS3/JavaScript讲义（附CD光盘）',57.40);
insert into books values(NULL,'精通CSS：高级Web标准解决方案（第2版）',39.00);
insert into books values(NULL,'HTML5移动Web开发指南',49.30);
insert into books values(NULL,'软件开发视频大讲堂：HTML5从入门到精通（附光盘1张）',50.20);
insert into books values(NULL,'Head First HTML5 Programming（中文版）',63.30);
insert into books values(NULL,'CSS权威指南（第3版）',47.00);
insert into books values(NULL,'HTML5+CSS3从入门到精通（附光盘）',52.60);
insert into books values(NULL,'Head First HTML与CSS（第2版）',83.70);
insert into books values(NULL,'HTML CSS JavaScript网页制作从入门到精通',34.60);
insert into books values(NULL,'精通CSS：高级Web标准解决方案（第2版）',39.00);
insert into books values(NULL,'CSS+DIV网页样式与布局从入门到精通（附光盘）',58.80);
insert into books values(NULL,'HTML5权威指南',112.30);
insert into books values(NULL,'HTML5与CSS3基础教程（第8版）',58.50);
insert into books values(NULL,'Web设计与前端开发秘籍：HTML CSS JavaScript jQuery 构建网站（套装共2册）',114.30);
insert into books values(NULL,'疯狂HTML 5/CSS3/JavaScript讲义（附CD光盘）',57.40);
insert into books values(NULL,'软件开发视频大讲堂：Java从入门到精通（第3版 附光盘）',38.00);
insert into books values(NULL,'Java编程思想（第4版）',71.30);
insert into books values(NULL,'疯狂Java讲义（第3版 附光盘）',74.20);
insert into books values(NULL,'Java核心技术（卷1）：基础知识（原书第9版）',85.60);
insert into books values(NULL,"O'Reilly：Head First Java（中文版 第2版 涵盖Java5.0）",52.00);
insert into books values(NULL,'Effective Java中文版（第2版）',45.70);
insert into books values(NULL,'深入理解Java虚拟机：JVM高级特性与最佳实践（第2版）',55.20);
insert into books values(NULL,'Java并发编程的艺术',49.60);
insert into books values(NULL,'轻量级Java EE企业应用实战：Struts2+Spring4+Hibernate整合开发（第4版 附CD光盘）',94.00);
insert into books values(NULL,'数据结构与算法分析：Java语言描述（第2版）',46.50);
insert into books values(NULL,'PHP和MySQL Web开发（原书第4版）',66.50);
insert into books values(NULL,'软件开发视频大讲堂：PHP从入门到精通（第3版 附光盘）',57.60);
insert into books values(NULL,'跟兄弟连学PHP（附光盘）',100.30);
insert into books values(NULL,'细说PHP（第2版）（含DVD光盘1张）',94.90);
insert into books values(NULL,'深入PHP：面向对象、模式与实践（第3版）',48.70);
insert into books values(NULL,'PHP开发实例大全（基础卷 附光盘）',108.80);
insert into books values(NULL,'PHP核心技术与最佳实践',75.10);
insert into books values(NULL,'Modern PHP（中文版）',31.20);
insert into books values(NULL,'PHP编程（第3版）',84.20);
insert into books values(NULL,'PHP经典实例（第3版）',108.10);
